const level1 = new Level(
    [
        new Pufferfish(),
        new Pufferfish(),
        new Pufferfish(),
        new Endboss(),
    ],
[
    new Light('assets/3.Background/Layers/1. Light/1.png', 500 ,0),
    new Light('assets/3.Background/Layers/1. Light/1.png', 1200 ,0),
    new Light('assets/3.Background/Layers/1. Light/1.png', 2290 ,0),
    new Light('assets/3.Background/Layers/1. Light/1.png', 1700 ,0),
],
[
    new Background('assets/3.Background/Layers/5. Water/D2.png', -720,0),
    new Background('assets/3.Background/Layers/4.Fondo 2/D2.png', -720,0),
    new Background('assets/3.Background/Layers/3.Fondo 1/D2.png', -720,0),
    new Background('assets/3.Background/Layers/2. Floor/D2.png', -720,0),
    new Background('assets/3.Background/Layers/5. Water/D1.png', 0,0),
    new Background('assets/3.Background/Layers/4.Fondo 2/D1.png', 0,0),
    new Background('assets/3.Background/Layers/3.Fondo 1/D1.png', 0,0),
    new Background('assets/3.Background/Layers/2. Floor/D1.png', 0,0),
    new Background('assets/3.Background/Layers/5. Water/D2.png', 720,0),
    new Background('assets/3.Background/Layers/4.Fondo 2/D2.png', 720,0),
    new Background('assets/3.Background/Layers/3.Fondo 1/D2.png', 720,0),
    new Background('assets/3.Background/Layers/2. Floor/D2.png', 720,0),
    new Background('assets/3.Background/Layers/5. Water/D1.png', 720*2,0),
    new Background('assets/3.Background/Layers/4.Fondo 2/D1.png',720*2,0),
    new Background('assets/3.Background/Layers/3.Fondo 1/D1.png',720*2,0),
    new Background('assets/3.Background/Layers/2. Floor/D1.png',720*2,0),
    new Background('assets/3.Background/Layers/5. Water/D2.png', 720*3,0),
    new Background('assets/3.Background/Layers/4.Fondo 2/D2.png', 720*3,0),
    new Background('assets/3.Background/Layers/3.Fondo 1/D2.png', 720*3,0),
    new Background('assets/3.Background/Layers/2. Floor/D2.png', 720*3,0),
]
);
